TEMPLATE = subdirs
SUBDIRS  = \
    smoke \
    accessibility \
    adblock \
    addbookmarkdialog \
    aroraicon \
    autosaver \
    bookmarknode \
    bookmarksmodel \
    browserapp \
    browsermainwindow \
    certerror \
    cookiejar \
    cookiemodel \
    containermanager \
    csp \
    devtools \
    dialogs \
    domainblock \
    downloadmanager \
    historyfiltermodel \
    historymanager \
    historyui \
    httponly \
    locationbar \
    modelmenu \
    modeltoolbar \
    networkaccessmanager \
    networkcookiejar \
    opensearchengine \
    opensearchmanager \
    opensearchreader \
    opensearchwriter \
    popupblocker \
    privatebrowsing \
    privacy \
    qrcode \
    rustdownload \
    safetext \
    sandbox \
    schemehandlers \
    scriptcontrol \
    securestore \
    searchlineedit \
    settingsdialog \
    singleapplication \
    sitepanel \
    tabbar \
    tabwidget \
    toolbarsearch \
    tormanager \
    urlcleaner \
    utils \
    webactionmapper \
    webpage \
    webpermissions \
    webview \
    xbel

CONFIG += ordered
