/*
 * Copyright 2026 The Arora Authors
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA  02110-1301  USA
 */

#include "bwrapgenerator.h"

#include "sandboxpolicy.h"

namespace BwrapGenerator {

QStringList commandLine(const SandboxPolicy &policy,
                        const QString &program,
                        const QStringList &programArgs)
{
    QStringList command;
    // bwrap needs a user namespace to create the mount tree; nested
    // namespaces are what lets Chromium's own renderer sandbox keep
    // working inside the wrap.  Network, pid and IPC namespaces stay
    // shared — this is a filesystem sandbox, not full isolation.
    command << QStringLiteral("bwrap")
            << QStringLiteral("--die-with-parent")
            << QStringLiteral("--setenv") << QStringLiteral("ARORA_SANDBOXED")
            << QStringLiteral("bwrap")
            << QStringLiteral("--dev-bind") << QStringLiteral("/")
            << QStringLiteral("/");
    for (const QString &dir : policy.deniedDirs)
        command << QStringLiteral("--tmpfs") << dir;
    for (const QString &file : policy.deniedFiles)
        command << QStringLiteral("--ro-bind") << QStringLiteral("/dev/null")
                << file;
    for (const QString &root : policy.readOnlyRoots)
        command << QStringLiteral("--ro-bind") << root << root;
    command << QStringLiteral("--") << program;
    command << programArgs;
    return command;
}

QString launcherScript()
{
    // The denylist is emitted as one entry per line and the script
    // word-splits on newlines only — space-bearing entries (the macOS
    // ~/Library/Application Support paths) survive intact.  The final
    // `set -- $wrap_args ...` rebuilds the positional parameters while
    // the caller's own "$@" is still appended verbatim.
    const QString denyEntries =
        SandboxPolicy::homeRelativeDeniedPaths().join(QLatin1Char('\n'));
    const QString readOnlyEntries =
        SandboxPolicy::readOnlyRootCandidates().join(QLatin1Char('\n'));

    QString script = QStringLiteral(
        "#!/bin/sh\n"
        "# arora-sandbox — start Arora inside the permissive bwrap\n"
        "# filesystem sandbox.  Generated by\n"
        "# BwrapGenerator::launcherScript() (src/sandbox/); the\n"
        "# autotest asserts this file matches the generator output, so\n"
        "# edit the generator rather than this file.\n"
        "set -ef\n"
        "bindir=$(CDPATH= cd -- \"$(dirname -- \"$0\")\" && pwd)\n"
        "bwrap=${ARORA_BWRAP:-$(command -v bwrap 2>/dev/null || true)}\n"
        "if [ -z \"$bwrap\" ] || [ -n \"$ARORA_NO_SANDBOX\" ]; then\n"
        "    exec \"$bindir/arora\" \"$@\"\n"
        "fi\n"
        "nl='\n"
        "'\n"
        "wrap_args=\"--die-with-parent$nl--setenv${nl}ARORA_SANDBOXED${nl}bwrap\"\n"
        "wrap_args=\"$wrap_args$nl--dev-bind${nl}/${nl}/\"\n"
        "denied_dirs=\"\n"
    );
    script += denyEntries;
    script += QStringLiteral(
        "\n\"\n"
        "read_only_roots=\"\n"
    );
    script += readOnlyEntries;
    script += QStringLiteral(
        "\n\"\n"
        "IFS=$nl\n"
        "for rel in $denied_dirs; do\n"
        "    p=$HOME/$rel\n"
        "    if [ -d \"$p\" ]; then\n"
        "        wrap_args=\"$wrap_args$nl--tmpfs$nl$p\"\n"
        "    elif [ -e \"$p\" ] || [ -L \"$p\" ]; then\n"
        "        wrap_args=\"$wrap_args$nl--ro-bind${nl}/dev/null$nl$p\"\n"
        "    fi\n"
        "done\n"
        "for root in $read_only_roots; do\n"
        "    if [ -d \"$root\" ]; then\n"
        "        wrap_args=\"$wrap_args$nl--ro-bind$nl$root$nl$root\"\n"
        "    fi\n"
        "done\n"
        "# IFS is still newline-only: $wrap_args splits into one\n"
        "# positional parameter per line (space-safe), then \"$@\"\n"
        "# appends the caller's arguments verbatim.\n"
        "set -- $wrap_args -- \"$bindir/arora\" \"$@\"\n"
        "unset IFS\n"
        "exec \"$bwrap\" \"$@\"\n"
    );
    return script;
}

} // namespace BwrapGenerator
