/*
 * Copyright 2026 The Arora Authors
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA  02110-1301  USA
 */

#include "platformgenerators.h"

#include "sandboxpolicy.h"

#include <QXmlStreamWriter>

namespace {

QString seatbeltQuoted(const QString &path)
{
    QString quoted = path;
    quoted.replace(QLatin1Char('\\'), QStringLiteral("\\\\"));
    quoted.replace(QLatin1Char('"'), QStringLiteral("\\\""));
    return quoted;
}

} // namespace

namespace SeatbeltGenerator {

QString profile(const SandboxPolicy &policy)
{
    QString out = QStringLiteral(
        ";; Arora sandbox profile — generated by SeatbeltGenerator\n"
        ";; (src/sandbox/platformgenerators.cpp).  Permissive policy:\n"
        ";; everything is allowed except the credential denylist,\n"
        ";; which loses read AND write access (a writable\n"
        ";; ~/.ssh/authorized_keys would defeat read-only masking).\n"
        "(version 1)\n"
        "(allow default)\n");
    for (const QString &dir : policy.deniedDirs) {
        out += QStringLiteral("(deny file-read* file-write* (subpath \"")
            + seatbeltQuoted(dir) + QStringLiteral("\"))\n");
    }
    for (const QString &file : policy.deniedFiles) {
        out += QStringLiteral("(deny file-read* file-write* (literal \"")
            + seatbeltQuoted(file) + QStringLiteral("\"))\n");
    }
    return out;
}

QString downloadWorkerProfile(const QString &workDir,
                              const QString &destDir)
{
    QString out = QStringLiteral(
        ";; Arora download-worker profile — generated by\n"
        ";; SeatbeltGenerator::downloadWorkerProfile.  Restrictive\n"
        ";; policy: deny default, then grant the minimum a downloader\n"
        ";; needs.  $HOME is never exposed — matching the Linux bwrap\n"
        ";; worker wrap (SAND02).\n"
        "(version 1)\n"
        "(deny default)\n"
        ";; dyld, Qt frameworks and resolver data.\n"
        "(allow file-read* (subpath \"/usr\"))\n"
        "(allow file-read* (subpath \"/System\"))\n"
        "(allow file-read* (subpath \"/Library\"))\n"
        "(allow file-read* (subpath \"/private/etc\"))\n"
        "(allow file-read* file-write* (subpath \"/dev\"))\n"
        ";; Qt + system services a bare QtCore process still needs.\n"
        "(allow mach-lookup)\n"
        "(allow sysctl-read)\n"
        "(allow network-outbound)\n");
    for (const QString &dir : {workDir, destDir}) {
        if (dir.isEmpty())
            continue;
        out += QStringLiteral("(allow file-read* file-write* (subpath \"")
            + seatbeltQuoted(dir) + QStringLiteral("\"))\n");
    }
    return out;
}

} // namespace SeatbeltGenerator

namespace AppContainerGenerator {

QString manifestXml(const SandboxPolicy &policy)
{
    QString xml;
    QXmlStreamWriter writer(&xml);
    writer.setAutoFormatting(true);
    writer.writeStartDocument();
    writer.writeStartElement(QStringLiteral("appContainerProfile"));
    writer.writeAttribute(QStringLiteral("name"), QStringLiteral("Arora"));

    writer.writeStartElement(QStringLiteral("capabilities"));
    // The policy allows networking — browsing needs it; AppContainer
    // requires an explicit capability or outbound traffic is denied.
    for (const QString &capability : {
            QStringLiteral("internetClient"),
            QStringLiteral("internetClientServer"),
            QStringLiteral("privateNetworkClientServer")}) {
        writer.writeEmptyElement(QStringLiteral("capability"));
        writer.writeAttribute(QStringLiteral("name"), capability);
    }
    writer.writeEndElement(); // capabilities

    writer.writeStartElement(QStringLiteral("fileRules"));
    for (const QString &dir : policy.deniedDirs) {
        writer.writeEmptyElement(QStringLiteral("rule"));
        writer.writeAttribute(QStringLiteral("path"), dir);
        writer.writeAttribute(QStringLiteral("access"),
                              QStringLiteral("deny"));
    }
    for (const QString &file : policy.deniedFiles) {
        writer.writeEmptyElement(QStringLiteral("rule"));
        writer.writeAttribute(QStringLiteral("path"), file);
        writer.writeAttribute(QStringLiteral("access"),
                              QStringLiteral("deny"));
    }
    for (const QString &root : policy.readOnlyRoots) {
        writer.writeEmptyElement(QStringLiteral("rule"));
        writer.writeAttribute(QStringLiteral("path"), root);
        writer.writeAttribute(QStringLiteral("access"),
                              QStringLiteral("read"));
    }
    writer.writeEndElement(); // fileRules
    writer.writeEndElement(); // appContainerProfile
    writer.writeEndDocument();
    return xml;
}

QString downloadWorkerManifestXml(const QString &workDir,
                                  const QString &destDir)
{
    QString xml;
    QXmlStreamWriter writer(&xml);
    writer.setAutoFormatting(true);
    writer.writeStartDocument();
    writer.writeStartElement(QStringLiteral("appContainerProfile"));
    writer.writeAttribute(QStringLiteral("name"),
                          QStringLiteral("AroraDownloadWorker"));

    writer.writeStartElement(QStringLiteral("capabilities"));
    // internetClient only: a downloader needs outbound HTTP(S) but
    // not inbound listeners or LAN access.
    writer.writeEmptyElement(QStringLiteral("capability"));
    writer.writeAttribute(QStringLiteral("name"),
                          QStringLiteral("internetClient"));
    writer.writeEndElement(); // capabilities

    writer.writeStartElement(QStringLiteral("fileRules"));
    for (const QString &dir : {workDir, destDir}) {
        if (dir.isEmpty())
            continue;
        writer.writeEmptyElement(QStringLiteral("rule"));
        writer.writeAttribute(QStringLiteral("path"), dir);
        writer.writeAttribute(QStringLiteral("access"),
                              QStringLiteral("write"));
    }
    writer.writeEndElement(); // fileRules
    writer.writeEndElement(); // appContainerProfile
    writer.writeEndDocument();
    return xml;
}

} // namespace AppContainerGenerator

namespace OpenBsdGenerator {

OpenBsdPlan plan(const SandboxPolicy &policy)
{
    OpenBsdPlan plan;
    // unveil(2): paths become visible only through unveiled rules and
    // the most recent unveil for a path wins, so the broad grant over
    // "/" is emitted first (matching bwrap's --dev-bind / /) and each
    // denylist entry re-veils itself with empty permissions — access
    // denied.  The read-only roots narrow the "/" grant afterwards.
    plan.unveilRules << QStringLiteral("/|rwc");
    for (const QString &root : policy.readOnlyRoots)
        plan.unveilRules << root + QStringLiteral("|r");
    for (const QString &dir : policy.deniedDirs)
        plan.unveilRules << dir + QStringLiteral("|");
    for (const QString &file : policy.deniedFiles)
        plan.unveilRules << file + QStringLiteral("|");
    // A web browser touches essentially every promise class; the list
    // is documented as near-vacuous hardening, not strong isolation.
    plan.pledgePromises = QStringLiteral(
        "stdio rpath wpath cpath inet unix dns proc exec thread ps "
        "audio video sendfd recvfd prot_exec");
    return plan;
}

OpenBsdPlan downloadWorkerPlan(const QString &workDir,
                               const QString &destDir)
{
    OpenBsdPlan plan;
    // No broad "/" grant — the worker sees only what a downloader
    // needs.  unveil(2) rules are ordered; all of these are additive
    // grants since nothing wider precedes them.
    for (const QString &root : {
            QStringLiteral("/usr"), QStringLiteral("/etc"),
            QStringLiteral("/var"), QStringLiteral("/tmp")})
        plan.unveilRules << root + QStringLiteral("|r");
    plan.unveilRules << workDir + QStringLiteral("|rwc");
    if (destDir != workDir)
        plan.unveilRules << destDir + QStringLiteral("|rwc");
    // The crate spawns threads (reqwest blocking + segment workers)
    // but never forks or execs; audio/video/proc/exec stay pledged
    // away.  prot_exec stays: the JIT-less engine maps no W+X pages,
    // but mapped library segments need it to run at all.
    plan.pledgePromises = QStringLiteral(
        "stdio rpath wpath cpath inet dns unix thread sendfd recvfd "
        "prot_exec");
    return plan;
}

} // namespace OpenBsdGenerator
