/*
 * Copyright 2026 The Arora Authors
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA  02110-1301  USA
 */

#include "platformgenerators.h"

#include "sandboxpolicy.h"

#include <QXmlStreamWriter>

namespace {

QString seatbeltQuoted(const QString &path)
{
    QString quoted = path;
    quoted.replace(QLatin1Char('\\'), QStringLiteral("\\\\"));
    quoted.replace(QLatin1Char('"'), QStringLiteral("\\\""));
    return quoted;
}

} // namespace

namespace SeatbeltGenerator {

QString profile(const SandboxPolicy &policy)
{
    QString out = QStringLiteral(
        ";; Arora sandbox profile — generated by SeatbeltGenerator\n"
        ";; (src/sandbox/platformgenerators.cpp).  Permissive policy:\n"
        ";; everything is allowed except the credential denylist,\n"
        ";; which loses read AND write access (a writable\n"
        ";; ~/.ssh/authorized_keys would defeat read-only masking).\n"
        "(version 1)\n"
        "(allow default)\n");
    for (const QString &dir : policy.deniedDirs) {
        out += QStringLiteral("(deny file-read* file-write* (subpath \"")
            + seatbeltQuoted(dir) + QStringLiteral("\"))\n");
    }
    for (const QString &file : policy.deniedFiles) {
        out += QStringLiteral("(deny file-read* file-write* (literal \"")
            + seatbeltQuoted(file) + QStringLiteral("\"))\n");
    }
    return out;
}

} // namespace SeatbeltGenerator

namespace AppContainerGenerator {

QString manifestXml(const SandboxPolicy &policy)
{
    QString xml;
    QXmlStreamWriter writer(&xml);
    writer.setAutoFormatting(true);
    writer.writeStartDocument();
    writer.writeStartElement(QStringLiteral("appContainerProfile"));
    writer.writeAttribute(QStringLiteral("name"), QStringLiteral("Arora"));

    writer.writeStartElement(QStringLiteral("capabilities"));
    // The policy allows networking — browsing needs it; AppContainer
    // requires an explicit capability or outbound traffic is denied.
    for (const QString &capability : {
            QStringLiteral("internetClient"),
            QStringLiteral("internetClientServer"),
            QStringLiteral("privateNetworkClientServer")}) {
        writer.writeEmptyElement(QStringLiteral("capability"));
        writer.writeAttribute(QStringLiteral("name"), capability);
    }
    writer.writeEndElement(); // capabilities

    writer.writeStartElement(QStringLiteral("fileRules"));
    for (const QString &dir : policy.deniedDirs) {
        writer.writeEmptyElement(QStringLiteral("rule"));
        writer.writeAttribute(QStringLiteral("path"), dir);
        writer.writeAttribute(QStringLiteral("access"),
                              QStringLiteral("deny"));
    }
    for (const QString &file : policy.deniedFiles) {
        writer.writeEmptyElement(QStringLiteral("rule"));
        writer.writeAttribute(QStringLiteral("path"), file);
        writer.writeAttribute(QStringLiteral("access"),
                              QStringLiteral("deny"));
    }
    for (const QString &root : policy.readOnlyRoots) {
        writer.writeEmptyElement(QStringLiteral("rule"));
        writer.writeAttribute(QStringLiteral("path"), root);
        writer.writeAttribute(QStringLiteral("access"),
                              QStringLiteral("read"));
    }
    writer.writeEndElement(); // fileRules
    writer.writeEndElement(); // appContainerProfile
    writer.writeEndDocument();
    return xml;
}

} // namespace AppContainerGenerator

namespace OpenBsdGenerator {

OpenBsdPlan plan(const SandboxPolicy &policy)
{
    OpenBsdPlan plan;
    // unveil(2): paths become visible only through unveiled rules and
    // the most recent unveil for a path wins, so the broad grant over
    // "/" is emitted first (matching bwrap's --dev-bind / /) and each
    // denylist entry re-veils itself with empty permissions — access
    // denied.  The read-only roots narrow the "/" grant afterwards.
    plan.unveilRules << QStringLiteral("/|rwc");
    for (const QString &root : policy.readOnlyRoots)
        plan.unveilRules << root + QStringLiteral("|r");
    for (const QString &dir : policy.deniedDirs)
        plan.unveilRules << dir + QStringLiteral("|");
    for (const QString &file : policy.deniedFiles)
        plan.unveilRules << file + QStringLiteral("|");
    // A web browser touches essentially every promise class; the list
    // is documented as near-vacuous hardening, not strong isolation.
    plan.pledgePromises = QStringLiteral(
        "stdio rpath wpath cpath inet unix dns proc exec thread ps "
        "audio video sendfd recvfd prot_exec");
    return plan;
}

} // namespace OpenBsdGenerator
